

services:
  app:
    build: .
    container_name: backend-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cantina
    volumes:
      - .:/app
      - ./dist:/app/dist
    command: sh -c "sleep 5 && \
                    npx prisma db pull --schema=prisma/schema.prisma && \
                    npx prisma generate --schema=prisma/schema.prisma && \
                    npx prisma db seed && \
                    yarn dev"

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cantina
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
