

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: backend-app-prod
    image: cozinha-backend:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
      - NODE_ENV=production
    command: sh -c "sleep 5 && \
                    npx prisma migrate deploy --schema=prisma/schema.prisma && \
                    yarn start"
    restart: always